services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: ./docker/php
    container_name: php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: netshoes
      MYSQL_USER: netshoes
      MYSQL_PASSWORD: netshoes
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  node:
    image: node:24.6
    container_name: node
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    tty: true
    stdin_open: true
    command: sh -c "npm install && npm run dev"

volumes:
  mysql_data:
